# Generated by Django 5.1.4 on 2025-10-02 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listing", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="listing.property",
            ),
        ),
    ]
