# Generated by Django 5.1.4 on 2025-10-02 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listing", "0003_alter_image_property"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyfeature",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="features",
                to="listing.property",
            ),
        ),
    ]
