# Generated by Django 5.1.4 on 2025-01-10 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_initial'),
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='property_paid_for',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='property_payments', to='listing.property'),
            preserve_default=False,
        ),
    ]
