# Generated by Django 5.1.1 on 2024-10-09 09:58

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='slug',
            field=models.SlugField(default=backend.models.generate_unique_slug),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='slug',
            field=models.SlugField(default=backend.models.generate_unique_slug),
        ),
        migrations.AlterField(
            model_name='payment',
            name='slug',
            field=models.SlugField(default=backend.models.generate_unique_slug),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(default=backend.models.generate_unique_slug),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='slug',
            field=models.SlugField(default=backend.models.generate_unique_slug),
        ),
    ]
