# Generated by Django 4.2.16 on 2024-10-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_owner_remove_property_image_remove_property_landlord_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Property_Features',
            new_name='PropertyFeature',
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('sold', 'Sold'), ('pending', 'Pending'), ('available', 'Available')], default='available', max_length=20),
        ),
    ]
