# Generated by Django 5.1.2 on 2024-10-11 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_cart_slug_alter_order_slug_and_more'),
        ('backend', '0005_alter_property_options_cart_created_at'),
    ]

    operations = [
    ]
