# Generated by Django 4.2.16 on 2024-10-11 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_merge_20241011_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='client',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='dob',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('returned', 'Returned'), ('pending', 'pending')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='backend.order'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('bank', 'Bank'), ('mpesa', 'Mpesa'), ('paypal', 'Paypal'), ('stripe', 'stripe')], default='mpesa', max_length=30),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('paid', 'paid'), ('refunded', 'refunded'), ('failed', 'failed'), ('unsettled', 'unsettled')], default='unsettled', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund'), ('authorization', 'Authorization'), ('chargeback', 'Chargeback'), ('adjustment', 'Adjustment'), ('payout', 'Payout')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
