# Generated by Django 4.2.16 on 2024-10-11 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_rename_name_agent_agent_rename_name_owner_owner_and_more'),
    ]

    operations = [
    ]
