# Generated by Django 4.2.16 on 2024-10-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
